# Generated by Django 5.1.2 on 2024-11-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_date_birth',
            field=models.DateField(null=True),
        ),
    ]
